### ISSUE TITLE
Did you apply the StaMarker for the other slices of DLPFC dataset?

### ISSUE THREAD

**Issue by keyalone** [messcode/STAMarker#9]
Hi:
   STAMarker is highly innovative, and its results are very convincing. The ensemble-based learning method offers a novel approach to spatial domain detection. I noticed that the authors applied STAMarker only to slice 151507 of the DLPFC datasets and it's grateful that the authors provide the tutorial for the reproduce experimental results of sclice 151507. I am currently interested in applying STAMarker to all slices of the DLPFC. I would greatly appreciate it if the authors could provide the code for the DLPFC dataset. Alternatively, could the authors offer guidances on the parameter settings for applying STAMarker to the all slices of DLPFC datasets? My email address is lihs@zjut.edu.cn. I look forward to the authors' response. Thank you.

Best regards.

**Comment by messcode** [comment]
Hi keyalone

I applied the STAMarker to all slices of the DLPFC data. I used the same settings across the entire dataset, except for n_classes, which was set to the number of layers corresponding to each slice. 

```  yaml
dataset:
  name: DLPFC
  type: 10xVisum
  data_dir: ../datasets/DLPFC/
  section: 151673
  n_classes: 7

preprocessing:
  rad_cutoff: 150
  n_top_genes: 3000
  show_net_stats: false
```

Alternatively, you can set the `model.clustering`, `model.consensus_clustering`, and `train_classifiers` to the correct number of classes. Additionally, I have re-implemented the consensus_clustering using linear sum assignment to accelerate it. I also added functions to analyze the data (see [T2  Human DLPFC 10x Visum dataset](./tutorial/Human-DLPFC-10x-Visum.ipynb)). I hope this helps.
